import json
import os
import re
from typing import Optional, Sequence, Set
from urllib import error, request

OLLAMA_DEFAULT_URL = "http://localhost:11434/v1/chat/completions"
OLLAMA_DEFAULT_MODEL = "llama3.1"


class LLMConversationAssistant:
    """Handles conversational replies and tool extraction via OLLAMA. All answers come from the model."""

    def __init__(self, config: dict | None = None) -> None:
        config = config or {}
        self._url = (
            str(config.get("url") or os.getenv("AUTO_AGENT_OLLAMA_URL", "")).strip()
            or str(config.get("url") or os.getenv("AUTO_AGENT_LLM_URL", "")).strip()
            or os.getenv("AUTO_AGENT_DEFAULT_LLM_URL", "").strip()
            or OLLAMA_DEFAULT_URL
        )
        self._api_key = (
            str(config.get("api_key") or os.getenv("AUTO_AGENT_OLLAMA_API_KEY", "")).strip()
            or str(config.get("api_key") or os.getenv("AUTO_AGENT_LLM_API_KEY", "")).strip()
        )
        self._model = (
            str(config.get("model") or os.getenv("AUTO_AGENT_OLLAMA_MODEL", "")).strip()
            or str(config.get("model") or os.getenv("AUTO_AGENT_LLM_MODEL", "")).strip()
            or os.getenv("AUTO_AGENT_DEFAULT_LLM_MODEL", "").strip()
            or OLLAMA_DEFAULT_MODEL
        )
        timeout_value = str(
            config.get("timeout")
            or os.getenv("AUTO_AGENT_OLLAMA_TIMEOUT", "")
            or os.getenv("AUTO_AGENT_LLM_TIMEOUT", "")
            or os.getenv("AUTO_AGENT_DEFAULT_LLM_TIMEOUT", "")
            or "30"
        ).strip()
        try:
            self._timeout = float(timeout_value) if timeout_value else 30.0
        except ValueError:
            self._timeout = 30.0

    def is_available(self) -> bool:
        return bool(self._url)

    def resolve(
        self,
        user_text: str,
        allowed_actions: Set[str],
        history: Sequence[dict[str, str]],
    ) -> Optional[dict]:
        if not self.is_available() or not user_text.strip():
            return None

        prompt = (
            "You are an assistant inside a desktop automation app connected to OLLAMA. "
            "ALL answers must come from the OLLAMA model; never use hard-coded replies. "
            "If the user asks a general question, answer conversationally and helpfully. "
            "If the user asks to perform a system task, return JSON tool call data. "
            "Preferred JSON shapes are:\n"
            '1) Chat response: {"type": "chat", "response": "..."}\n'
            '2) Tool call: {"type": "tool", "action": "...", "target": "...", '
            '"destination": "..."}\n'
            "Only use actions from this whitelist: "
            f"{sorted(allowed_actions)}. "
            "Use type=chat for general Q&A. Use type=tool when the user clearly requests a task. "
            "Do not hallucinate flatpak/snap/package IDs - if unsure about exact ID, answer with type=chat and explain how to search (e.g. flatpak search, dnf search) instead of guessing. "
            "Every response must be generated by the model."
        )

        messages = [{"role": "system", "content": prompt}]
        messages.extend(history[-6:])
        messages.append({"role": "user", "content": user_text})

        payload = {
            "model": self._model,
            "messages": messages,
            "temperature": 0.2,
            "stream": False,
        }

        raw = self._post_json(payload)
        if raw is None:
            return None

        parsed = self._extract_json(raw)
        if not parsed:
            plain_text = self._extract_text(raw)
            if plain_text:
                return {"type": "chat", "response": plain_text}
            return None

        if not self._validate_schema(parsed):
            return None

        item_type = str(parsed.get("type", "")).strip().lower()
        if item_type == "chat":
            response = str(parsed.get("response", "")).strip()
            if response:
                return {"type": "chat", "response": response}
            return None

        if item_type == "tool":
            action = str(parsed.get("action", "")).strip()
            if action not in allowed_actions:
                return None

            target = str(parsed.get("target", "")).strip()
            destination = str(parsed.get("destination", "")).strip()
            return {
                "type": "tool",
                "action": action,
                "target": target,
                "destination": destination,
            }

        return None

    def _validate_schema(self, payload: dict) -> bool:
        item_type = payload.get("type")
        if not isinstance(item_type, str):
            return False

        normalized = item_type.strip().lower()
        if normalized == "chat":
            return isinstance(payload.get("response"), str) and bool(str(payload.get("response", "")).strip())

        if normalized == "tool":
            action_ok = isinstance(payload.get("action"), str) and bool(str(payload.get("action", "")).strip())
            target_ok = "target" not in payload or isinstance(payload.get("target"), str)
            destination_ok = "destination" not in payload or isinstance(payload.get("destination"), str)
            return action_ok and target_ok and destination_ok

        return False

    def _extract_text(self, response_json: dict) -> str | None:
        content = (
            response_json.get("choices", [{}])[0]
            .get("message", {})
            .get("content", "")
        )
        if not isinstance(content, str) or not content.strip():
            content = response_json.get("message", {}).get("content", "")
            if not isinstance(content, str) or not content.strip():
                return None

        text = content.strip()
        if not text:
            return None

        if text.startswith("```"):
            return None

        return text

    def _post_json(self, payload: dict) -> Optional[dict]:
        body = json.dumps(payload).encode("utf-8")
        headers = {"Content-Type": "application/json"}
        if self._api_key:
            headers["Authorization"] = f"Bearer {self._api_key}"

        req = request.Request(self._url, data=body, headers=headers, method="POST")
        try:
            with request.urlopen(req, timeout=self._timeout) as response:
                return json.loads(response.read().decode("utf-8"))
        except (error.URLError, error.HTTPError, json.JSONDecodeError, TimeoutError, OSError):
            if self._url.endswith("/v1/chat/completions"):
                native_url = self._url.replace("/v1/chat/completions", "/api/chat")
                native_payload = {
                    "model": self._model,
                    "messages": payload["messages"],
                    "stream": False,
                }
                native_body = json.dumps(native_payload).encode("utf-8")
                native_req = request.Request(native_url, data=native_body, headers=headers, method="POST")
                try:
                    with request.urlopen(native_req, timeout=self._timeout) as resp:
                        native_raw = json.loads(resp.read().decode("utf-8"))
                        content = native_raw.get("message", {}).get("content", "")
                        if content:
                            return {"choices": [{"message": {"content": content}}]}
                        return native_raw
                except Exception:
                    return None
            return None

    def _extract_json(self, response_json: dict) -> Optional[dict]:
        if isinstance(response_json, dict) and "type" in response_json:
            return response_json

        content = (
            response_json.get("choices", [{}])[0]
            .get("message", {})
            .get("content", "")
        )
        if not isinstance(content, str) or not content.strip():
            content = response_json.get("message", {}).get("content", "")
            if not isinstance(content, str):
                return None

        text = content.strip()
        if text.startswith("{") and text.endswith("}"):
            try:
                parsed = json.loads(text)
                if isinstance(parsed, dict):
                    return parsed
            except json.JSONDecodeError:
                return None

        match = re.search(r"\{.*\}", text, re.DOTALL)
        if not match:
            return None

        try:
            parsed = json.loads(match.group(0))
            return parsed if isinstance(parsed, dict) else None
        except json.JSONDecodeError:
            return None
